### ISSUE TITLE
PyPI Name

### ISSUE THREAD

**Issue by jarrodchesney** [dcramer/peek#1]
Hi @dcramer 
I was wondering if it'd be possible to have your packages name "peek" on pypi.

If it's not an inconvenience would you be kind enough to let me have it?

**Comment by phiweger** [comment]
Same here -- are you able to free the PyPi name?

**Comment by alexmojaki** [comment]
Haha I also want it, I'm guessing it's not going to happen.

**Comment by dcramer** [comment]
Just pick a different name.

**Comment by jarrodchesney** [comment]
Cool, Your new name is "david-cramer-peek", let me know when you've changed it.

On 21 May 2019, at 2:09 am, David Cramer <notifications@github.com<mailto:notifications@github.com>> wrote:


Just pick a different name.
